baseURL = 'https://btromm.github.io/'
languageCode = 'en-us'
title = 'bobby tromm'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-DCHF3FSFSJ"

[caches]
   [caches.images]
      dir = ':cacheDir/images'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "personal website of bobby tromm"

# Hero image (path relative to static folder)
#heroImage = "/images/hero.jpeg"

# Appearance settings
theme = 'light'
colorPalette = 'default'
hideHeader = true # Hide header on home page
showTags = true

showFooter = true
footerContent = "copyright &copy; 1234. made with [hugo](https://gohugo.io/) and [typo](https://github.com/tomfran/typo)"

# Intro on main page, content is markdown
homeIntroTitle = ""
homeIntroContent = """
I'm a neuroscience and machine learning PhD student at UCL, supervised by Caswell Barry and Tim Behrens. I work on biologically plausible representations, with a focus on first-principles: given space & metabolic constraints, how should a brain represent and process information to best support adaptive behaviour?

Previously, I was an engineer in the [Neuronal Circuits & Brain Dynamics](https://www.neuronaldynamics.eu/) group in Paris, a visiting researcher at the
[Centre for Eudaimonia and Human Flourishing](https://hedonia.kringelbach.org/) in Oxford, and an RA with [Eve Marder](https://sites.google.com/brandeis.edu/marder-lab/) at Brandeis.
"""

# Collection to display on home
homeCollectionTitle = 'recent'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = false
home = "Home"

# Social icons
[[params.social]]
name = "gmail"
url = "mailto:robert.tromm.25@ucl.ac.uk"

[[params.social]]
name = "github"
url = "https://github.com/btromm"

[[params.social]]
name = "googlescholar"
url = "https://scholar.google.com/citations?user=hJl27VcAAAAJ&hl=en"

[[params.social]]
name = "twitter"
url = "https://x.com/b_tromm"

# Main menu pages
[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "publications"
url = "/publications"

[[params.menu]]
name = "cv"
url = "/pdf/cv.pdf"

[[params.menu]]
name = "photos"
url = '/photos'

# Syntax highlight on code blocks
[markup]
   [markup.goldmark.renderer]
      unsafe = true
   [markup.highlight]
      style = 'algol'

# Table of contents configuration
[markup.tableOfContents]
endLevel = 4   # Include headings up to h4
ordered = false
startLevel = 2

# Giscus comments
[params.giscus]
enable = false
repo = "btromm/btromm.github.io"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[params.author]
    name = "Bobby Tromm"
    email = "bobby.tromm@gmail.com"
