baseURL = 'https://btromm.github.io/'
languageCode = 'en-us'
title = 'bobby tromm'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-DCHF3FSFSJ"

[caches]
   [caches.images]
      dir = ':cacheDir/images'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "a blog about neuroscience, complexity, intelligence, and consciousness"

# Hero image (path relative to static folder)
heroImage = "/images/hero.jpeg"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = true # Hide header on home page
showTags = true

showFooter = true
footerContent = "copyright &copy; 2025. made with [hugo](https://gohugo.io/) and [typo](https://github.com/tomfran/typo)"

# Intro on main page, content is markdown
homeIntroTitle = "bio"
homeIntroContent = """
I'm a neuroscientist interested in how brains interact with consciousness. My research is centered around understanding how the structure and dynamics of neural activity give rise to cognition and consciousness.

I'm currently self-studying mathematics and machine learning -- you can view some of my writing on that [here](https://example.com).

Previously, I was an engineer in the [Neuronal Circuits & Brain Dynamics](https://www.neuronaldynamics.eu/) 
group at the Paris Brain Institute and a visiting researcher at the
[Centre for Eudaimonia and Human Flourishing](https://hedonia.kringelbach.org/) in Oxford,
where I worked with Morten Kringelbach. I received my bachelor's degree from Brandeis University, 
where I unsuccessfully solved [neuronal homeostasis](https://github.com/btromm/neuralcorr-thesis/blob/057526cd442187a4b39891109806a88541d18150/thesis/Thesis/BobbyTromm_Thesis2020.pdf) 
under [Eve Marder](https://sites.google.com/brandeis.edu/marder-lab/).

In my free time, I like reading, climbing, and dancing left/right/left/right to repetitive techno rhythms. I also meditate, and (occasionally) write.
"""

# Collection to display on home
homeCollectionTitle = 'recent'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = false
home = "Home"

# Social icons
[[params.social]]
name = "bluesky"
url = "https://bsky.app/profile/btromm.bsky.social"

[[params.social]]
name = "twitter"
url = "https://x.com/b_tromm"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/btromm/"

[[params.social]]
name = "github"
url = "https://github.com/btromm"

# Main menu pages
[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "notes"
url = "/notes"

[[params.menu]]
name = "publications"
url = "/publications"

[[params.menu]]
name = "cv"
url = "/pdf/cv.pdf"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Table of contents configuration
[markup.tableOfContents]
endLevel = 4   # Include headings up to h4
ordered = false
startLevel = 2

# Giscus comments
[params.giscus]
enable = false
repo = "btromm/btromm.github.io"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

[outputs]
  home = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[Author]
    name = "Bobby Tromm"
    email = "bobby.tromm@gmail.com"
