
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'bobby tromm'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-DCHF3FSFSJ"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "a blog on consciousness"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = ''
homeIntroContent = """
i'm a neuroscientist interested in how brains interact with consciousness.
"""

# Collection to display on home
homeCollectionTitle = 'posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "bluesky"
url = "https://bsky.app/profile/btromm.bsky.social"

[[params.social]]
name = "twitter"
url = "https://x.com/b_tromm"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/btromm/"

[[params.social]]
name = "github"
url = "https://github.com/btromm"

# Main menu pages

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "publications"
url = "/publications"

[[params.menu]]
name = "cv"
url = "/cv"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
